package com.jonny.healthtrack.util

import android.content.Context
import android.content.Intent
import android.graphics.Bitmap
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.Rect
import android.graphics.Typeface
import android.net.Uri
import android.text.TextPaint
import androidx.core.content.FileProvider
import java.io.File
import java.io.FileOutputStream
import java.time.LocalDate
import java.time.format.DateTimeFormatter
import java.util.Locale

object ShareUtils {

    fun shareDaySummary(context: Context, date: LocalDate, components: List<AggregatedComponent>) {
        val bitmap = generateSummaryBitmap(context, date, components)
        val file = saveBitmapToCache(context, bitmap)
        shareImage(context, file)
    }

    private fun generateSummaryBitmap(context: Context, date: LocalDate, components: List<AggregatedComponent>): Bitmap {
        // Config
        val width = 1080
        val padding = 60f
        val headerHeight = 250f
        val rowHeight = 100f
        val footerHeight = 100f
        
        // Calculate total height
        val totalHeight = (headerHeight + (components.size * rowHeight) + footerHeight).toInt()
        
        val bitmap = Bitmap.createBitmap(width, totalHeight, Bitmap.Config.ARGB_8888)
        val canvas = Canvas(bitmap)
        
        // Paints
        val bgPaint = Paint().apply { color = Color.WHITE }
        val titlePaint = TextPaint().apply {
            color = Color.BLACK
            textSize = 80f
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
            isAntiAlias = true
        }
        val datePaint = TextPaint().apply {
            color = Color.DKGRAY
            textSize = 48f
            isAntiAlias = true
        }
        val itemPaint = TextPaint().apply {
            color = Color.BLACK
            textSize = 42f
            isAntiAlias = true
        }
        val quantityPaint = TextPaint().apply {
            color = Color.parseColor("#4CAF50") // Primary Green
            textSize = 42f
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
            isAntiAlias = true
            textAlign = Paint.Align.RIGHT
        }
        val footerPaint = TextPaint().apply {
            color = Color.GRAY
            textSize = 36f
            textAlign = Paint.Align.CENTER
            isAntiAlias = true
        }
        val linePaint = Paint().apply {
            color = Color.LTGRAY
            strokeWidth = 2f
        }

        // Draw Background
        canvas.drawRect(0f, 0f, width.toFloat(), totalHeight.toFloat(), bgPaint)

        // Draw Header
        val dateStr = date.format(DateTimeFormatter.ofPattern("EEEE, MMM d, yyyy"))
        canvas.drawText("Daily Summary", padding, 120f, titlePaint)
        canvas.drawText(dateStr, padding, 200f, datePaint)
        
        // Draw Separator
        canvas.drawLine(padding, headerHeight - 20, width - padding, headerHeight - 20, linePaint)

        // Draw Items
        var currentY = headerHeight + 60 // Start slightly below header
        
        components.forEach { component ->
            val emoji = getEmojiForComponent(component.keyName)
            val name = component.displayName
            val qtyString = String.format(Locale.US, "%.1f %s", component.quantity, component.unit ?: "").trim()
            
            // Draw Emoji + Name
            canvas.drawText("$emoji  $name", padding, currentY, itemPaint)
            
            // Draw Quantity (Right Aligned)
            canvas.drawText(qtyString, width - padding, currentY, quantityPaint)
            
            currentY += rowHeight
        }

        // Footer
        val footerY = totalHeight - 40f
        canvas.drawText("Generated by OmniTracker", width / 2f, footerY, footerPaint)

        return bitmap
    }

    private fun getEmojiForComponent(key: String): String {
        return when (key.lowercase()) {
            "energy" -> "⚡"
            "net weight" -> "⚖️"
            "protein" -> "🐟"
            "carbohydrate" -> "🥐"
            "total fat" -> "💧"
            "saturated fat" -> "🍔"
            "dietary fiber" -> "🌿"
            "sugar" -> "🍦"
            "sodium" -> "🌊"
            "potassium" -> "🍌"
            "cholesterol" -> "💓"
            "caffeine" -> "☕"
            else -> "🔹"
        }
    }

    private fun saveBitmapToCache(context: Context, bitmap: Bitmap): File {
        val cachePath = File(context.cacheDir, "images")
        cachePath.mkdirs()
        val stream = FileOutputStream("$cachePath/daily_summary.png")
        bitmap.compress(Bitmap.CompressFormat.PNG, 100, stream)
        stream.close()
        return File(cachePath, "daily_summary.png")
    }

    private fun shareImage(context: Context, file: File) {
        val uri = FileProvider.getUriForFile(
            context,
            "${context.packageName}.fileprovider",
            file
        )
        val intent = Intent(Intent.ACTION_SEND).apply {
            type = "image/png"
            putExtra(Intent.EXTRA_STREAM, uri)
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
        }
        context.startActivity(Intent.createChooser(intent, "Share Daily Summary"))
    }
}
